services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: eventstore
      POSTGRES_PASSWORD: eventstore
      POSTGRES_DB: eventstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: eventstore
      MONGO_INITDB_ROOT_PASSWORD: eventstore
    volumes:
      - mongo-data:/data/db

volumes:
  postgres_data:
    driver: local
  mongo-data:
    driver: local
